// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcTla4fKlFFWxeaNWRyrYbCHMRRuol51w',
    appId: '1:241298580805:web:a26f082054f8128a2f4a2c',
    messagingSenderId: '241298580805',
    projectId: 'airyzone-life-app',
    authDomain: 'airyzone-life-app.firebaseapp.com',
    storageBucket: 'airyzone-life-app.appspot.com',
    measurementId: 'G-VN9KLVRMJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIpYE5jphnAEeMcy4PEPs4b-gBvvfo-TY',
    appId: '1:241298580805:android:b72be9a4ed1c70802f4a2c',
    messagingSenderId: '241298580805',
    projectId: 'airyzone-life-app',
    storageBucket: 'airyzone-life-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwwZu6-MlbIgxQQPpp9dAQg1zUmCxwgwI',
    appId: '1:241298580805:ios:b1ff3a002dec57672f4a2c',
    messagingSenderId: '241298580805',
    projectId: 'airyzone-life-app',
    storageBucket: 'airyzone-life-app.appspot.com',
    iosClientId: '241298580805-rov62ccuftaqf8iv1b81a6jh1bi7etr6.apps.googleusercontent.com',
    iosBundleId: 'com.testing.life',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwwZu6-MlbIgxQQPpp9dAQg1zUmCxwgwI',
    appId: '1:241298580805:ios:f7a46843a2ae0ee62f4a2c',
    messagingSenderId: '241298580805',
    projectId: 'airyzone-life-app',
    storageBucket: 'airyzone-life-app.appspot.com',
    iosClientId: '241298580805-oap4deit2mh67ihr4v9al9t03efmt9c5.apps.googleusercontent.com',
    iosBundleId: 'com.testing.life.RunnerTests',
  );
}
